version: '3.9'

services:
  web:
    build: .
    container_name: psycho_app
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: >
      sh -c "sleep 3 && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    container_name: psycho_app_postgres
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
